#!MC 1100
$!VarSet |MFBD| = './'
$!READDATASET  ''
READDATAOPTION = NEW
RESETSTYLE = YES
INCLUDETEXT = NO
INCLUDEGEOM = NO
INCLUDECUSTOMLABELS = NO
VARLOADMODE = BYNAME
ASSIGNSTRANDIDS = YES
INITIALPLOTTYPE = CARTESIAN3D
VARNAMELIST = '"x" "y" "z" "rho" "u" "v" "w" "p" '
 $!FIELDLAYERS SHOWMESH = NO
 $!GLOBALCONTOUR 1  VAR = 4
 $!CONTOURLEVELS RESETTONICE
CONTOURGROUP = 1
APPROXNUMVALUES = 15
$!FIELDLAYERS SHOWCONTOUR = YES
